-- Tabla para registrar los pagos a ganadores
CREATE TABLE IF NOT EXISTS pagos (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    RADICADO VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    HORA TIME NOT NULL,
    CODANIMAL INT NOT NULL,
    ANIMAL VARCHAR(50) NOT NULL,
    CODIGOJ INT NOT NULL,
    HORAJUEGO VARCHAR(50),
    VALOR_APOSTADO DECIMAL(10,2) NOT NULL,
    VALOR_GANADO DECIMAL(10,2) NOT NULL,
    SUCURSAL INT NOT NULL,
    USUARIO VARCHAR(50) NOT NULL,
    ESTADO VARCHAR(1) DEFAULT 'A', -- A=Activo/Pagado, C=Cancelado
    FECHA_PAGO DATETIME NOT NULL,
    OBSERVACIONES TEXT,
    INDEX idx_radicado (RADICADO),
    INDEX idx_fecha (FECHA),
    INDEX idx_sucursal (SUCURSAL),
    INDEX idx_estado (ESTADO),
    FOREIGN KEY (SUCURSAL) REFERENCES bodegas(CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabla para control de cierre de juegos
CREATE TABLE IF NOT EXISTS cierrejuego (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CODIGOH INT NOT NULL,
    HORAJUEGO VARCHAR(50) NOT NULL,
    FECHA DATE NOT NULL,
    TOTAL_APOSTADO DECIMAL(12,2) DEFAULT 0,
    TOTAL_PAGADO DECIMAL(12,2) DEFAULT 0,
    UTILIDAD DECIMAL(12,2) DEFAULT 0,
    COMISION_ADMIN DECIMAL(12,2) DEFAULT 0,
    COMISION_SISTEMA DECIMAL(12,2) DEFAULT 0,
    GANANCIA_SUCURSAL DECIMAL(12,2) DEFAULT 0,
    CODANIMAL_GANADOR INT,
    ANIMAL_GANADOR VARCHAR(50),
    ESTADO VARCHAR(1) DEFAULT 'A', -- A=Abierto, C=Cerrado
    FECHA_CIERRE DATETIME,
    USUARIO_CIERRE VARCHAR(50),
    OBSERVACIONES TEXT,
    INDEX idx_fecha (FECHA),
    INDEX idx_horario (CODIGOH),
    INDEX idx_estado (ESTADO),
    UNIQUE KEY unique_horario_fecha (CODIGOH, FECHA),
    FOREIGN KEY (CODIGOH) REFERENCES horariojuego(NUM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
