/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Ruleta;

import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DESINCO
 */
public class FrmDGanadores extends javax.swing.JDialog {

    Conexion ConeBD =  new Conexion();
    
    int Ingreso = 0, Consecu = 0;
    
    DefaultTableModel DatosLottoG;
    String DatLottoG[] =  new String[6];
    
    Timer Tiempo;
    java.util.Date Reloj;
    SimpleDateFormat Formato;
    
    DecimalFormat Convertir = new DecimalFormat("###,###.##"); 
    
    double ValTJugar = 0;
    String HoraJuego = "", FechaJuego = "";
    
    public FrmDGanadores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try
        {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());            
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FechaInicial = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaGanadores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 3, 1, 3, new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Fecha Juego:");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones_1/iconfinder_11_4698581.png"))); // NOI18N
        jButton1.setText("Buscar Ganadores");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FechaInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TablaGanadores.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TablaGanadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaGanadores.setRowHeight(30);
        jScrollPane1.setViewportView(TablaGanadores);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 997, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void MostrarGanadores()
    {
        String SqlMostrarGanadores = "";
        
        TablaGanadores.clearSelection();
        DatosLottoG = new DefaultTableModel();
        TablaGanadores.setModel(DatosLottoG);
        DatosLottoG.addColumn("Radicado");
        DatosLottoG.addColumn("Lotto Animal");
        DatosLottoG.addColumn("Valor Apostado $");
        DatosLottoG.addColumn("Fecha");
        DatosLottoG.addColumn("Hora");
        DatosLottoG.addColumn("Hora Jugada");
        
        try
        {
            SqlMostrarGanadores = "SELECT hislottojuego.RADICADO AS NUMJUEGO, hislottojuego.CODANIMAL AS CODA,"
                    + " hislottojuego.ANIMAL AS NOMANIMAL, hislottojuego.VALOR AS VALORJ,"
                    + " hislottojuego.FECHA AS FECHA, hislottojuego.HORA AS HORAJ, ingresarganadores.DESCRIOCIONH AS HORAJUEGO"
                    + " FROM hislottojuego, ingresarganadores"
                    + " WHERE"
                    + " ingresarganadores.CODIGOA = hislottojuego.CODANIMAL AND ingresarganadores.CODIGOH = hislottojuego.CODIGOJ AND"
                    + " ingresarganadores.FECHA = '"+FechaJuego+"' AND hislottojuego.FECHA = '"+FechaJuego+"' AND hislottojuego.ESTADOP = 'A'";
            ConeBD.RstBD = (ResultSet) ConeBD.StmBD.executeQuery(SqlMostrarGanadores);
            while (ConeBD.RstBD.next())
            {
                DatLottoG[0] = ConeBD.RstBD.getString("NUMJUEGO");
                DatLottoG[1] = ConeBD.RstBD.getString("NOMANIMAL");
                DatLottoG[2] = String.valueOf(Convertir.format(ConeBD.RstBD.getDouble("VALORJ")));
                DatLottoG[3] = String.valueOf(ConeBD.RstBD.getDate("FECHA"));
                DatLottoG[4] = String.valueOf(ConeBD.RstBD.getTime("HORAJ"));
                DatLottoG[5] = ConeBD.RstBD.getString("HORAJUEGO");
                DatosLottoG.addRow(DatLottoG);
            }
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }
    }
    
    void BuscarGanadores()
    {
        java.util.Date fechaS = FechaInicial.getDate();
        SimpleDateFormat S = new SimpleDateFormat("yyyy-MM-dd");
        String FechaI = (S.format(fechaS));
        
        String SqlMostrarGanadores = "";
        
        TablaGanadores.clearSelection();
        DatosLottoG = new DefaultTableModel();
        TablaGanadores.setModel(DatosLottoG);
        DatosLottoG.addColumn("Radicado");
        DatosLottoG.addColumn("Lotto Animal");
        DatosLottoG.addColumn("Valor Apostado $");
        DatosLottoG.addColumn("Fecha");
        DatosLottoG.addColumn("Hora");
        DatosLottoG.addColumn("Hora Jugada");
        
        try
        {
            SqlMostrarGanadores = "SELECT hislottojuego.RADICADO AS NUMJUEGO, hislottojuego.CODANIMAL AS CODA,"
                    + " hislottojuego.ANIMAL AS NOMANIMAL, hislottojuego.VALOR AS VALORJ,"
                    + " hislottojuego.FECHA AS FECHA, hislottojuego.HORA AS HORAJ, ingresarganadores.DESCRIOCIONH AS HORAJUEGO"
                    + " FROM hislottojuego, ingresarganadores"
                    + " WHERE"
                    + " ingresarganadores.CODIGOA = hislottojuego.CODANIMAL AND ingresarganadores.CODIGOH = hislottojuego.CODIGOJ AND"
                    + " ingresarganadores.FECHA = '"+FechaI+"' AND hislottojuego.FECHA = '"+FechaI+"' AND hislottojuego.ESTADOP = 'A'";
            System.out.println(SqlMostrarGanadores);
            ConeBD.RstBD = (ResultSet) ConeBD.StmBD.executeQuery(SqlMostrarGanadores);            
            while (ConeBD.RstBD.next())
            {
                DatLottoG[0] = ConeBD.RstBD.getString("NUMJUEGO");
                DatLottoG[1] = ConeBD.RstBD.getString("NOMANIMAL");
                DatLottoG[2] = String.valueOf(Convertir.format(ConeBD.RstBD.getDouble("VALORJ")));
                DatLottoG[3] = String.valueOf(ConeBD.RstBD.getDate("FECHA"));
                DatLottoG[4] = String.valueOf(ConeBD.RstBD.getTime("HORAJ"));
                DatLottoG[5] = ConeBD.RstBD.getString("HORAJUEGO");
                DatosLottoG.addRow(DatLottoG);
            }
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        BuscarGanadores();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ConeBD.Coneccion_BD();
        
        SimpleDateFormat F = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date Fecha = new java.util.Date();
        FechaInicial.setDate(Fecha);
        FechaJuego = String.valueOf(F.format(Fecha));
        MostrarGanadores();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDGanadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDGanadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDGanadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDGanadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                FrmDGanadores dialog = new FrmDGanadores(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser FechaInicial;
    private javax.swing.JTable TablaGanadores;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
