/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Ruleta;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author OMGM
 */
public class FrmDSeguridad extends javax.swing.JDialog {

    Conexion ConeBD =  new Conexion();
    int Ingreso = 0;
    String Clave = "";
    DefaultTableModel DatosSeguridad;
    String DatSeguridad[] =  new String[5];
    
    public FrmDSeguridad(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try
        {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());            
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtNick = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtClave = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        TxtConClave = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        CmbTipo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        CmbEstado = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaSeguridad = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 3, 1, 3, new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Identificación:");

        TxtId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TxtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtIdKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nombre:");

        TxtNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nick:");

        TxtNick.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Clave:");

        TxtClave.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Confirmar Clave:");

        TxtConClave.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Tipo:");

        CmbTipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CmbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione ...", "Admon", "Sucursal" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Estado:");

        CmbEstado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CmbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione ...", "Activo", "Inactivo" }));

        TablaSeguridad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TablaSeguridad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaSeguridad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TablaSeguridad.setRowHeight(25);
        TablaSeguridad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaSeguridadMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaSeguridad);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/icons/add.png"))); // NOI18N
        jButton1.setText("Nuevo");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/icons/accept.png"))); // NOI18N
        jButton2.setText("Guardar");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/icons/database_edit.png"))); // NOI18N
        jButton3.setText("Editar");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/icons/cross.png"))); // NOI18N
        jButton4.setText("Eliminar");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/icons/group_add.png"))); // NOI18N
        jButton5.setText("<html>\n<center>\n\tCambio de\n\t<br>\n\tClave\n</center>\n<html>");
        jButton5.setActionCommand("");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtId)
                    .addComponent(TxtNick)
                    .addComponent(CmbTipo, 0, 132, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TxtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtConClave, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 144, Short.MAX_VALUE))
                            .addComponent(TxtNombre)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane1)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtNick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(TxtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(TxtConClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(CmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ConeBD.Coneccion_BD();
        Apagar();
        ListarTabla();
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Ingreso = 1;
        Prender();
        Limpiar();
    }//GEN-LAST:event_jButton1ActionPerformed
    void ListarTabla()
    {
        String SqlMostrar = "";
        TablaSeguridad.clearSelection();
        DatosSeguridad =  new DefaultTableModel();
        TablaSeguridad.setModel(DatosSeguridad);
        DatosSeguridad.addColumn("Id");
        DatosSeguridad.addColumn("Nombre");
        DatosSeguridad.addColumn("Nick");
        DatosSeguridad.addColumn("Tipo");
        DatosSeguridad.addColumn("Estado");
        try
        {
            SqlMostrar = "SELECT *  FROM SEGURIDAD";
            ConeBD.RstBD = (ResultSet) ConeBD.StmBD.executeQuery(SqlMostrar);
            while (ConeBD.RstBD.next())
            {
                DatSeguridad[0] = ConeBD.RstBD.getString("ID");
                DatSeguridad[1] = ConeBD.RstBD.getString("NOMBRE");
                DatSeguridad[2] = ConeBD.RstBD.getString("NICK");
                DatSeguridad[3] = ConeBD.RstBD.getString("TIPO");
                DatSeguridad[4] = ConeBD.RstBD.getString("ESTADO");
                DatosSeguridad.addRow(DatSeguridad);
            }
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }
    }
    void Limpiar()
    {
        TxtClave.setText("");
        TxtConClave.setText("");
        TxtId.setText("");
        TxtNick.setText("");
        TxtNombre.setText("");
        CmbEstado.setSelectedIndex(0);
        CmbTipo.setSelectedIndex(0);
    }
    void Apagar()
    {        
        TxtClave.setEnabled(false);
        TxtConClave.setEnabled(false);
        TxtId.setEnabled(false);
        TxtNick.setEnabled(false);
        TxtNombre.setEnabled(false);
        CmbEstado.setEnabled(false);
        CmbTipo.setEnabled(false);        
    }
    void Prender()
    {
        
        TxtClave.setEnabled(true);
        TxtConClave.setEnabled(true);
        TxtId.setEnabled(true);
        TxtNick.setEnabled(true);
        TxtNombre.setEnabled(true);
        CmbEstado.setEnabled(true);
        CmbTipo.setEnabled(true);
        TxtId.requestFocus();
    }
    void Guardar()
    {
        String SqlGuardar = "";
        try
        {
            SqlGuardar = "INSERT INTO SEGURIDAD VALUES ('"+TxtId.getText()+"','"+TxtNombre.getText()+"','"+
                    TxtNick.getText()+"','"+TxtConClave.getText()+"','"+CmbTipo.getSelectedIndex()+"',1,0"+",'"+CmbEstado.getSelectedIndex()+"')";
            System.out.println(SqlGuardar);
            ConeBD.StmBD.executeUpdate(SqlGuardar);
            JOptionPane.showMessageDialog(null, "El Usuario se Creo Exitosamente ...");
            Limpiar();
            Apagar();
            ListarTabla();
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }
    }
    void Editar()
    {
        String SqlEditar = "";
        try
        {
            SqlEditar = "UPDATE SEGURIDAD SET NOMBRE = '"+TxtNombre.getText()+"', NICK = '"+TxtNick.getText()+"', TIPO = '"+
                    CmbTipo.getSelectedIndex()+"', ESTADO = '"+CmbEstado.getSelectedIndex()+"' WHERE "+
                    " ID = '"+TxtId.getText()+"'";
            ConeBD.StmBD.executeUpdate(SqlEditar);
            JOptionPane.showMessageDialog(null, "Usuario Modificado ...");
            Limpiar();
            Apagar();
            ListarTabla();
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }
    }
    void Eliminar()
    {
        String SqlEliminar = "";
        try
        {
            SqlEliminar = "DELETE FROM SEGURIDAD WHERE ID = '"+TxtId.getText()+"'";
            ConeBD.StmBD.executeUpdate(SqlEliminar);
            JOptionPane.showMessageDialog(null, "Usuario Sistema Eliminado ...");
            Limpiar();
            Apagar();
            ListarTabla();
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        switch (Ingreso)
        {
            case 1:
            {
                if (CmbTipo.getSelectedIndex() != 0)
                {
                    if (CmbEstado.getSelectedIndex() != 0)
                    {
                        Guardar();
                    }
                }                
            }
                break;
            case 2:
            {
                Editar();
            }
                break;
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    void SacarClave(String Id)
    {
        String SqlSacarClave = "";
        try
        {
            SqlSacarClave =  "SELECT CLAVE FROM SEGURIDAD WHERE ID = '"+Id+"'";
            ConeBD.RstBD = (ResultSet) ConeBD.StmBD.executeQuery(SqlSacarClave);
            if (ConeBD.RstBD.next())
            {
                Clave = ConeBD.RstBD.getString("CLAVE");
            }
                     
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }
    }
            
    private void TablaSeguridadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaSeguridadMouseClicked
        int Fila = TablaSeguridad.getSelectedRow();
        int Columna0 = 0, Columna1 = 1, Columna2 = 2, Columna3 = 3, Columna4 = 4;
        
        TxtId.setText((String.valueOf(this.TablaSeguridad.getValueAt(Fila, Columna0))));
        TxtNombre.setText((String.valueOf(this.TablaSeguridad.getValueAt(Fila, Columna1))));
        TxtNick.setText((String.valueOf(this.TablaSeguridad.getValueAt(Fila, Columna2))));
        CmbTipo.setSelectedIndex(Integer.parseInt((String.valueOf(this.TablaSeguridad.getValueAt(Fila, Columna3)))));
        CmbEstado.setSelectedIndex(Integer.parseInt((String.valueOf(this.TablaSeguridad.getValueAt(Fila, Columna4)))));
        SacarClave(TxtId.getText());
        
    }//GEN-LAST:event_TablaSeguridadMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Ingreso = 2;
        Prender();
        TxtClave.setEnabled(false);
        TxtConClave.setEnabled(false);
        TxtId.setEnabled(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int OpcG = JOptionPane.showConfirmDialog(null, "¿El Proceso Eliminara"+
        "\n El Usuario -- Desea Continuar ...?");
        if (OpcG == 0)
        {
            Eliminar();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (!(TxtId.getText().equals("")))
        {
            FrmDCambioClave CanC =  new FrmDCambioClave(null, rootPaneCheckingEnabled);
            CanC.Mostrar(TxtId.getText(), TxtNombre.getText(), Clave);
            CanC.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Debe Seleccionar un Usuario ...");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void TxtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtIdKeyTyped
        char c1 = evt.getKeyChar();
        if (c1 < '0' || c1 > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_TxtIdKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDSeguridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDSeguridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDSeguridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDSeguridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                FrmDSeguridad dialog = new FrmDSeguridad(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CmbEstado;
    private javax.swing.JComboBox CmbTipo;
    private javax.swing.JTable TablaSeguridad;
    private javax.swing.JPasswordField TxtClave;
    private javax.swing.JPasswordField TxtConClave;
    private javax.swing.JTextField TxtId;
    private javax.swing.JTextField TxtNick;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
