/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Ruleta;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author OMGM
 */
public class FrmDSucursal extends javax.swing.JDialog {

    
    Conexion ConeBD = new Conexion();
    
    int Consecu = 0, Ingreso = 0;
    
    DefaultTableModel DatosBodegas;    
    String DatBodegas[] = new String[2];
    
    String Codigo, Cate;
    
    public FrmDSucursal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try
        {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtSedes = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaSedes = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 3, 1, 3, new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Codigo:");

        TxtCodigo.setEditable(false);
        TxtCodigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TxtCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Sucursal:");

        TxtSedes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TxtSedes.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        TablaSedes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TablaSedes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaSedes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TablaSedes.setRowHeight(25);
        TablaSedes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaSedesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaSedes);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setText("Editar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtSedes)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(TxtSedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Ingreso = 1;
        Limpiar();
        Consecutivo();
        Prender();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        switch (Ingreso) {
            case 1: 
            {
                Guardar();
            }
            break;
            case 2: 
            {
                Editar();
            }
            break;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Ingreso = 2;
        Prender();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Eliminar();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void TablaSedesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaSedesMouseClicked
        int Fila = TablaSedes.getSelectedRow();
        int Columna0 = 0, Columna1 = 1; 
        
        Codigo = String.valueOf(this.TablaSedes.getValueAt(Fila, Columna0));
        Cate = String.valueOf(this.TablaSedes.getValueAt(Fila, Columna1));
        
        TxtCodigo.setText(Codigo);
        TxtSedes.setText(Cate);
    }//GEN-LAST:event_TablaSedesMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ConeBD.Coneccion_BD();
        Limpiar();
        Apagar();
        MostrarTabla();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    
    void MostrarTabla()
    {
        String SqlMostrarTabla = "";
        TablaSedes.clearSelection();
        DatosBodegas =  new DefaultTableModel();
        TablaSedes.setModel(DatosBodegas);
        
        DatosBodegas.addColumn("Codigo");
        DatosBodegas.addColumn("Bodega");
        
        try
        {
            SqlMostrarTabla = "SELECT * FROM BODEGAS ORDER BY CODIGO";
            ConeBD.RstBD = (ResultSet) ConeBD.StmBD.executeQuery(SqlMostrarTabla);
            while (ConeBD.RstBD.next())
            {
                DatBodegas[0] = String.valueOf(ConeBD.RstBD.getInt("CODIGO"));
                DatBodegas[1] = ConeBD.RstBD.getString("BODEGA");
                DatosBodegas.addRow(DatBodegas);
                
            }
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }
        
    }
    
    void Apagar()
    {
        TxtCodigo.setEnabled(false);
        TxtSedes.setEnabled(false);
    }
    void Prender()
    {
        TxtSedes.setEnabled(true);
        TxtSedes.requestFocus();
    }
    void Limpiar()
    {
        TxtCodigo.setText("");
        TxtSedes.setText("");
        TxtSedes.requestFocus();
    }
    
    void Consecutivo()
    {
        String SqlConse = "";
        try
        {
            SqlConse = "SELECT MAX(CODIGO) AS CONSECUTIVO FROM BODEGAS";
            ConeBD.RstBD = (ResultSet) ConeBD.StmBD.executeQuery(SqlConse);
            if (ConeBD.RstBD.next())
            {
                Consecu = ConeBD.RstBD.getInt("CONSECUTIVO") + 1;                
            }
            TxtCodigo.setText(String.valueOf(Consecu));
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }
    }
    
    void Guardar()
    {
        String SqlGuardar = "";
        if ((!TxtSedes.getText().equals("")))
        {
            try
            {
                SqlGuardar = "INSERT INTO BODEGAS VALUES ("+TxtCodigo.getText()+",'"+TxtSedes.getText()+"')";
                ConeBD.StmBD.executeUpdate(SqlGuardar);
                JOptionPane.showMessageDialog(null, "Bodega Creada y Almacenada ...");
                Limpiar();
                Apagar();
                MostrarTabla();
            }
            catch (Exception err)
            {
                err.printStackTrace();
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Debe Ingresar Una Bodega ...");        
        }
        
    }
    void Editar()
    {
        String SqlEditar = "";
        try
        {
            int OpcG = JOptionPane.showConfirmDialog(null, "¿El Proceso que Realizara Modificara"+
                "\n El Nombre de la Caja -- Desea Continuar ...?");
            if (OpcG == 0)
            {
                SqlEditar = "UPDATE BODEGAS SET CAJA = '"+TxtSedes.getText()+"' "+
                    " WHERE CODIGO = "+TxtCodigo.getText();
                ConeBD.StmBD.executeUpdate(SqlEditar);
                JOptionPane.showMessageDialog(null, "Bodega Modificada ...");
                Limpiar();
                Apagar();
                MostrarTabla();
            }   
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }
    }
    void Eliminar()
    {
        String SqlEliminar = "";
        
        try
        {
            int OpcG = JOptionPane.showConfirmDialog(null, "¿El Proceso Eliminara"+
                "\n La Caja -- Desea Continuar ...?");
            if (OpcG == 0)
            {
                SqlEliminar = "DELETE FROM BODEGAS WHERE CODIGO = "+TxtCodigo.getText();
                ConeBD.StmBD.executeUpdate(SqlEliminar);
                JOptionPane.showMessageDialog(null, "Bodega Eliminada ...");
                Limpiar();
                Apagar();
                MostrarTabla();
            }
        }
        catch(Exception err)
        {
            err.printStackTrace();
        }
    }
    
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                FrmDSucursal dialog = new FrmDSucursal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaSedes;
    private javax.swing.JTextField TxtCodigo;
    private javax.swing.JTextField TxtSedes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
