/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Ruleta;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author OMGM
 */
public class FrmDAsoUsuarioSeg extends javax.swing.JDialog {

    Conexion ConeBD =  new Conexion();
    
    
    DefaultTableModel DatosSeguridad;
    String DatSeguridad[] =  new String[5];
    
    public FrmDAsoUsuarioSeg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try
        {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());            
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaUsuarios = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        CmbSede = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        TxtCodBodega = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Id:");

        TxtId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TxtId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtIdKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nombre:");

        TxtNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TxtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtNombreKeyReleased(evt);
            }
        });

        TablaUsuarios.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TablaUsuarios.setRowHeight(25);
        TablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaUsuarios);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Sucursal:");

        CmbSede.setEditable(true);
        CmbSede.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CmbSede.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione ..." }));
        CmbSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbSedeActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Integrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        TxtCodBodega.setEditable(false);
        TxtCodBodega.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TxtCodBodega.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 266, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CmbSede, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtCodBodega, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CmbSede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(TxtCodBodega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void Limpiar()
    {
        TxtCodBodega.setText("");
        TxtId.setText("");
        TxtNombre.setText("");
//        CmbCaja.setSelectedIndex(0);
        CmbSede.setSelectedIndex(0);
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ConeBD.Coneccion_BD();
        IniciarTabla();
        ListarTabla();
        CargarBodegas();
    }//GEN-LAST:event_formWindowOpened

    private void TxtIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtIdKeyReleased
        
        if (!(TxtId.getText().equals("")))
        {
            FiltrarUsuario("ID", TxtId.getText());
        }
        else
        {
            IniciarTabla();
            ListarTabla();
        }
    }//GEN-LAST:event_TxtIdKeyReleased

    private void TxtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNombreKeyReleased
        if (!(TxtNombre.getText().equals("")))
        {
            FiltrarUsuario("NOMBRE", TxtNombre.getText());
        }
        else
        {
            IniciarTabla();
            ListarTabla();
        }
    }//GEN-LAST:event_TxtNombreKeyReleased

    private void TablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaUsuariosMouseClicked
        int Fila = TablaUsuarios.getSelectedRow();
        int Columna0 = 0, Columna1 = 1, Columna2 = 2, Columna3 = 3, Columna4 = 4;
        
        TxtId.setText((String.valueOf(this.TablaUsuarios.getValueAt(Fila, Columna0))));
        TxtNombre.setText((String.valueOf(this.TablaUsuarios.getValueAt(Fila, Columna1))));
    }//GEN-LAST:event_TablaUsuariosMouseClicked

    private void CmbSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbSedeActionPerformed
        String NomBodega = CmbSede.getSelectedItem().toString(), SqlSacarCodigo = "";
        
        try
        {
            SqlSacarCodigo = "SELECT CODIGO FROM BODEGAS WHERE BODEGA = '"+NomBodega+"'";
            ConeBD.RstBD = (ResultSet) ConeBD.StmBD.executeQuery(SqlSacarCodigo);
            if (ConeBD.RstBD.next())
            {
                TxtCodBodega.setText(String.valueOf(ConeBD.RstBD.getInt("CODIGO")));
            }
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }
    }//GEN-LAST:event_CmbSedeActionPerformed

    void IntegrarUsuario()
    {
        String SqlIntegrar = "";
        
        try
        {
            SqlIntegrar = "UPDATE SEGURIDAD SET CODBODEGA = "+
                    TxtCodBodega.getText()+" WHERE ID = '"+TxtId.getText()+"'";
            ConeBD.StmBD.executeUpdate(SqlIntegrar);
            JOptionPane.showMessageDialog(null, "Usuario : "+TxtNombre.getText()+" Integradoa a "
                    + "la Sucursal : "+CmbSede.getSelectedItem().toString());
            Limpiar();
        }
        catch (Exception err)
        {
            err.printStackTrace();                    
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int OpcG = JOptionPane.showConfirmDialog(null, "¿Desea Integrar el Usuario a la Sucursal?");
        if (OpcG == 0)
        {
            IntegrarUsuario();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    void CargarBodegas()
    {
        String SqlCargarCajas = "";
        
        try
        {
            SqlCargarCajas = "SELECT BODEGA FROM BODEGAS ORDER BY CODIGO";
            ConeBD.RstBD = (ResultSet) ConeBD.StmBD.executeQuery(SqlCargarCajas);
            while (ConeBD.RstBD.next())
            {
                CmbSede.addItem((ConeBD.RstBD.getString("BODEGA")));
            }
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }
    }
    
    void FiltrarUsuario(String Tabla, String Campo)
    {
        String SqlMostrar = "";
        IniciarTabla();
        try
        {
            SqlMostrar = "SELECT *  FROM SEGURIDAD WHERE "+Tabla+" LIKE '%"+Campo+"%'";
            ConeBD.RstBD = (ResultSet) ConeBD.StmBD.executeQuery(SqlMostrar);
            while (ConeBD.RstBD.next())
            {
                DatSeguridad[0] = ConeBD.RstBD.getString("ID");
                DatSeguridad[1] = ConeBD.RstBD.getString("NOMBRE");
                DatSeguridad[2] = ConeBD.RstBD.getString("NICK");
                DatSeguridad[3] = ConeBD.RstBD.getString("TIPO");
                DatSeguridad[4] = ConeBD.RstBD.getString("ESTADO");
                DatosSeguridad.addRow(DatSeguridad);
            }
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }
    }
    
    void IniciarTabla()
    {
        TablaUsuarios.clearSelection();
        DatosSeguridad =  new DefaultTableModel(){

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }            
        };
        TablaUsuarios.setModel(DatosSeguridad);
        DatosSeguridad.addColumn("Id");
        DatosSeguridad.addColumn("Nombre");
        DatosSeguridad.addColumn("Nick");
        DatosSeguridad.addColumn("Tipo");
        DatosSeguridad.addColumn("Estado");
    }
    
    void ListarTabla()
    {
        String SqlMostrar = "";        
        try
        {
            SqlMostrar = "SELECT *  FROM SEGURIDAD";
            ConeBD.RstBD = (ResultSet) ConeBD.StmBD.executeQuery(SqlMostrar);
            while (ConeBD.RstBD.next())
            {
                DatSeguridad[0] = ConeBD.RstBD.getString("ID");
                DatSeguridad[1] = ConeBD.RstBD.getString("NOMBRE");
                DatSeguridad[2] = ConeBD.RstBD.getString("NICK");
                DatSeguridad[3] = ConeBD.RstBD.getString("TIPO");
                DatSeguridad[4] = ConeBD.RstBD.getString("ESTADO");
                DatosSeguridad.addRow(DatSeguridad);
            }
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }
    }
    
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDAsoUsuarioSeg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDAsoUsuarioSeg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDAsoUsuarioSeg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDAsoUsuarioSeg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                FrmDAsoUsuarioSeg dialog = new FrmDAsoUsuarioSeg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CmbSede;
    private javax.swing.JTable TablaUsuarios;
    private javax.swing.JTextField TxtCodBodega;
    private javax.swing.JTextField TxtId;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
