/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Ruleta;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JViewport;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author DESINCO
 */
public class FrmDIngresarResultado extends javax.swing.JDialog {

    
    Conexion ConeBD =  new Conexion();
    
    int Ingreso = 0, Consecu = 0;
    
    DefaultTableModel DatosLotto;
    String DatLotto[] =  new String[4];
    
    DefaultTableModel DatosHorarioLotto;
    String DatHorarioLotto[] =  new String[4];
    
    DefaultTableModel DatosJugar;
    String DatJugar[] =  new String[5];
    
    Timer Tiempo;
    java.util.Date Reloj;
    SimpleDateFormat Formato;
    
    DecimalFormat Convertir = new DecimalFormat("###,###.##"); 
    
    double ValTJugar = 0;
    String HoraJuego = "";
    
    public FrmDIngresarResultado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try
        {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());            
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaRuleta = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaHorario = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        JlSucursal = new javax.swing.JLabel();
        JlHora = new javax.swing.JLabel();
        FechaJuego = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        TxtCodA = new javax.swing.JTextField();
        TxtAnimal = new javax.swing.JTextField();
        TxtHoraJuego = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        TxtCodigoH = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 3, 1, 3, new java.awt.Color(0, 0, 0)));

        TablaRuleta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TablaRuleta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaRuleta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TablaRuleta.setRowHeight(30);
        TablaRuleta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaRuletaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaRuleta);

        TablaHorario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TablaHorario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaHorario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TablaHorario.setRowHeight(25);
        TablaHorario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaHorarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaHorario);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Sucursal:");

        JlSucursal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JlSucursal.setText(".");

        JlHora.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JlHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlHora.setText("00:00:00");

        FechaJuego.setEnabled(false);
        FechaJuego.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JlSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(FechaJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JlHora, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JlSucursal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JlHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(FechaJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Animalito:");

        TxtCodA.setEditable(false);
        TxtCodA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxtCodA.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        TxtAnimal.setEditable(false);
        TxtAnimal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        TxtHoraJuego.setEditable(false);
        TxtHoraJuego.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TxtHoraJuego.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones_1/iconfinder_Cheque_5580232.png"))); // NOI18N
        jButton1.setText("Guardar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        TxtCodigoH.setEditable(false);
        TxtCodigoH.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TxtCodigoH.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtCodA, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TxtCodigoH, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtHoraJuego)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtCodA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtHoraJuego)
                    .addComponent(TxtCodigoH))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void MostrarHora()
    {
        Formato = new SimpleDateFormat("HH:mm:ss");
        Tiempo = new Timer(1000, new ActionListener() 
        {
            public void actionPerformed(ActionEvent evt)
            {
                Reloj = new java.util.Date();
                JlHora.setText(Formato.format(Reloj));
            }
        });
        Tiempo.start();
    }
    
    public void Mostrar(String Sucursal, Date FechaHTTP)
    {
        FechaJuego.setDate(FechaHTTP);
        
        JlSucursal.setText(Sucursal);
        MostrarHora();
    }
    
    void MostrarTablaJuegos()
    {
        String SqlMostrarTabla = "";
        TablaHorario.clearSelection();
        DatosHorarioLotto =  new DefaultTableModel();
        TablaHorario.setModel(DatosHorarioLotto);
        
        DatosHorarioLotto.addColumn("Codigo");
        DatosHorarioLotto.addColumn("Des. Juego");
        DatosHorarioLotto.addColumn("Hota Juego");
        
        try
        {
            //SqlMostrarTabla = "SELECT * FROM horariojuego WHERE (HORA < '"+JlHora.getText()+"') AND ESTADO = 'A' ORDER BY NUM";
            SqlMostrarTabla = "SELECT * FROM horariojuego WHERE ESTADO = 'A' ORDER BY NUM";
            System.out.println(SqlMostrarTabla);
            ConeBD.RstBD = (ResultSet) ConeBD.StmBD.executeQuery(SqlMostrarTabla);
            while (ConeBD.RstBD.next())
            {
                DatHorarioLotto[0] = String.valueOf(ConeBD.RstBD.getInt("NUM"));
                DatHorarioLotto[1] = ConeBD.RstBD.getString("DESCRIPCION");
                DatHorarioLotto[2] = String.valueOf(ConeBD.RstBD.getTime("HORA"));
                DatosHorarioLotto.addRow(DatHorarioLotto);
                
                int anchoColumna1 = 0;
                JViewport scroll1 =  (JViewport) TablaHorario.getParent();
                int ancho1 = scroll1.getWidth();
                TableColumnModel modeloColumna1 = TablaHorario.getColumnModel();
                TableColumn columnaTabla1;                
                for (int j = 0; j < TablaHorario.getColumnCount(); j++)
                {
                    columnaTabla1 = modeloColumna1.getColumn(j);
                    switch(j)
                    {
                        case 0: anchoColumna1 = (15*ancho1)/100;
                            break;
                        case 1: anchoColumna1 = (80*ancho1)/100;
                            break;
                        case 2: anchoColumna1 = (30*ancho1)/100;
                            break;
                    }
                    columnaTabla1.setPreferredWidth(anchoColumna1);
                }
                
            }
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }        
    }
    
    void MostrarTabla()
    {
        String SqlMostrarTabla = "";
        TablaRuleta.clearSelection();
        DatosLotto =  new DefaultTableModel();
        TablaRuleta.setModel(DatosLotto);
        
        DatosLotto.addColumn("Codigo");
        DatosLotto.addColumn("#");
        DatosLotto.addColumn("Animal");
        DatosLotto.addColumn("Color");
        
        try
        {
            SqlMostrarTabla = "SELECT * FROM lottoruleta WHERE ESTADO = 'A' ORDER BY NUM";
            ConeBD.RstBD = (ResultSet) ConeBD.StmBD.executeQuery(SqlMostrarTabla);
            while (ConeBD.RstBD.next())
            {
                DatLotto[0] = String.valueOf(ConeBD.RstBD.getInt("NUM"));
                DatLotto[1] = ConeBD.RstBD.getString("CODIGOJUEGO");
                DatLotto[2] = ConeBD.RstBD.getString("VALOR");
                DatLotto[3] = ConeBD.RstBD.getString("COLOR");
                TablaRuleta.setDefaultRenderer(Object.class,new Render());
                DatosLotto.addRow(DatLotto);
                
                int anchoColumna1 = 0;
                JViewport scroll1 =  (JViewport) TablaRuleta.getParent();
                int ancho1 = scroll1.getWidth();
                TableColumnModel modeloColumna1 = TablaRuleta.getColumnModel();
                TableColumn columnaTabla1;                
                for (int j = 0; j < TablaRuleta.getColumnCount(); j++)
                {
                    columnaTabla1 = modeloColumna1.getColumn(j);
                    switch(j)
                    {
                        case 0: anchoColumna1 = (15*ancho1)/100;
                            break;
                        case 1: anchoColumna1 = (15*ancho1)/100;
                            break;
                        case 2: anchoColumna1 = (50*ancho1)/100;
                            break;
                        case 3: anchoColumna1 = (15*ancho1)/100;
                            break;
                    }
                    columnaTabla1.setPreferredWidth(anchoColumna1);
                }
                
            }
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }        
    }
    
    void Limpiar()
    {
        TxtAnimal.setText("");
        TxtCodA.setText("");
        TxtCodigoH.setText("");
        TxtHoraJuego.setText("");
    }
    
    private void TablaRuletaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaRuletaMouseClicked

        int Fila = TablaRuleta.getSelectedRow();
        int Columna0 = 0, Columna1 = 1, Columna2 = 2, Columna3 = 3;

        TxtCodA.setText((String.valueOf(this.TablaRuleta.getValueAt(Fila, Columna1))));
        TxtAnimal.setText((String.valueOf(this.TablaRuleta.getValueAt(Fila, Columna2))));
//
//        TxtValorJ.requestFocus();
    }//GEN-LAST:event_TablaRuletaMouseClicked

    private void TablaHorarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaHorarioMouseClicked

        int Fila = TablaHorario.getSelectedRow();
        int Columna0 = 0, Columna1 = 1, Columna2 = 2, Columna3 = 3;

        TxtCodigoH.setText((String.valueOf(this.TablaHorario.getValueAt(Fila, Columna0))));
        TxtHoraJuego.setText((String.valueOf(this.TablaHorario.getValueAt(Fila, Columna1))));
        HoraJuego = (String.valueOf(this.TablaHorario.getValueAt(Fila, Columna2)));
//
//        jButton3.requestFocus();
    }//GEN-LAST:event_TablaHorarioMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ConeBD.Coneccion_BD();
        MostrarTabla();
        MostrarTablaJuegos();
    }//GEN-LAST:event_formWindowOpened

    void Guardar()
    {
        String SqlGuardar = "";
        
        java.util.Date fechaS = FechaJuego.getDate();
        SimpleDateFormat S = new SimpleDateFormat("yyyy-MM-dd");
        String FechaF = (S.format(fechaS));
        
        try
        {
            SqlGuardar = "INSERT INTO ingresarganadores VALUES ('"+TxtCodA.getText()+"','"+TxtAnimal.getText()+"',"
                    +TxtCodigoH.getText()+",'"+TxtHoraJuego.getText()+"','"+FechaF+"','A')";
            ConeBD.StmBD.executeUpdate(SqlGuardar);
            JOptionPane.showMessageDialog(null, "Resultado Ingresado en la Fecha : "+FechaF+" Hora de Juego : "+TxtHoraJuego.getText());
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int OpcG = JOptionPane.showConfirmDialog(null, "¿Desea Ingesar el resultado del Juego de Lotto Animal ...?");
        if (OpcG == 0)
        {
            Guardar();
            Limpiar();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDIngresarResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDIngresarResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDIngresarResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDIngresarResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                FrmDIngresarResultado dialog = new FrmDIngresarResultado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser FechaJuego;
    private javax.swing.JLabel JlHora;
    private javax.swing.JLabel JlSucursal;
    private javax.swing.JTable TablaHorario;
    private javax.swing.JTable TablaRuleta;
    private javax.swing.JTextField TxtAnimal;
    private javax.swing.JTextField TxtCodA;
    private javax.swing.JTextField TxtCodigoH;
    private javax.swing.JTextField TxtHoraJuego;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
