/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Ruleta;

import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DESINCO
 */
public class FrmDListarJugadas extends javax.swing.JDialog {

     Conexion ConeBD =  new Conexion();
    
    int Ingreso = 0, Consecu = 0, CodigoJuego = 0;
    
    DefaultTableModel DatosLottoJ;
    String DatLottoJ[] =  new String[7];
    
    Timer Tiempo;
    java.util.Date Reloj;
    SimpleDateFormat Formato;
    
    DecimalFormat Convertir = new DecimalFormat("###,###.##"); 
    
    double ValTJugar = 0;
    String HoraJuego = "";
    
    public FrmDListarJugadas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try
        {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());            
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FechaInicial = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CmbHorJuego = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaJugadas = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        JlJuego = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 3, 1, 3, new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Fecha Juego:");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones_1/iconfinder_Search_Social-01_1911363.png"))); // NOI18N
        jButton1.setText("Listar Juegos");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Hora de Juego:");

        CmbHorJuego.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CmbHorJuego.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione ..." }));
        CmbHorJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbHorJuegoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CmbHorJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FechaInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CmbHorJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TablaJugadas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TablaJugadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaJugadas.setRowHeight(30);
        jScrollPane1.setViewportView(TablaJugadas);

        JlJuego.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JlJuego.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlJuego.setText(".");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JlJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JlJuego, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ConeBD.Coneccion_BD();
        ListarHorJuegos();
        SimpleDateFormat F = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date Fecha = new java.util.Date();
        FechaInicial.setDate(Fecha);
    }//GEN-LAST:event_formWindowOpened

    void ListarJuegos()
    {
        java.util.Date fechaS = FechaInicial.getDate();
        SimpleDateFormat S = new SimpleDateFormat("yyyy-MM-dd");
        String FechaI = (S.format(fechaS));
        
        String SqlListarJuegos = "";
        
        TablaJugadas.clearSelection();
        DatosLottoJ =  new DefaultTableModel();
        TablaJugadas.setModel(DatosLottoJ);
        DatosLottoJ.addColumn("Radicado");
        DatosLottoJ.addColumn("Cod. Animal");
        DatosLottoJ.addColumn("Animal");
        DatosLottoJ.addColumn("Valor $");
        DatosLottoJ.addColumn("Sucursal");
        DatosLottoJ.addColumn("Hora");
        DatosLottoJ.addColumn("Estado");
        
        try
        {
            SqlListarJuegos = "SELECT * FROM hislottojuego WHERE CODIGOJ = "+CodigoJuego+" AND FECHA = '"+FechaI+"'";
            ConeBD.RstBD = (ResultSet) ConeBD.StmBD.executeQuery(SqlListarJuegos);
            while (ConeBD.RstBD.next())
            {
                DatLottoJ[0] = ConeBD.RstBD.getString("RADICADO");
                DatLottoJ[1] = String.valueOf(ConeBD.RstBD.getInt("CODANIMAL"));
                DatLottoJ[2] = ConeBD.RstBD.getString("ANIMAL");
                DatLottoJ[3] = String.valueOf(Convertir.format(ConeBD.RstBD.getDouble("VALOR")));
                DatLottoJ[4] = ConeBD.RstBD.getString("SUCURSAL");
                DatLottoJ[5] = String.valueOf(ConeBD.RstBD.getTime("HORA"));
                DatLottoJ[6] = ConeBD.RstBD.getString("ESTADOP");
                DatosLottoJ.addRow(DatLottoJ);
            }
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ListarJuegos();
    }//GEN-LAST:event_jButton1ActionPerformed

    void ListarHorJuegos()
    {
        String SqlListar = "";
        
        try
        {
            SqlListar = "SELECT DESCRIPCION FROM horariojuego ORDER BY NUM";
            ConeBD.RstBD = (ResultSet) ConeBD.StmBD.executeQuery(SqlListar);
            while (ConeBD.RstBD.next())
            {
                CmbHorJuego.addItem(ConeBD.RstBD.getString("DESCRIPCION"));
            }
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }
    }
    
    private void CmbHorJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbHorJuegoActionPerformed
        
        String NomJuego = CmbHorJuego.getSelectedItem().toString(), SqlSacarCodigo = "";
        JlJuego.setText(NomJuego);
        try
        {
            SqlSacarCodigo = "SELECT NUM FROM horariojuego WHERE DESCRIPCION = '"+NomJuego+"'";
            ConeBD.RstBD = (ResultSet) ConeBD.StmBD.executeQuery(SqlSacarCodigo);
            if (ConeBD.RstBD.next())
            {
                CodigoJuego = ConeBD.RstBD.getInt("NUM");
            }
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }
    }//GEN-LAST:event_CmbHorJuegoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDListarJugadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDListarJugadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDListarJugadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDListarJugadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                FrmDListarJugadas dialog = new FrmDListarJugadas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CmbHorJuego;
    private com.toedter.calendar.JDateChooser FechaInicial;
    private javax.swing.JLabel JlJuego;
    private javax.swing.JTable TablaJugadas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
