/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Ruleta;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author DESINCO
 */
public class FrmInicioP extends javax.swing.JFrame {

    
    Conexion ConeBD = new Conexion();
    int CodigoBodega = 0;
    
    public FrmInicioP() {
        initComponents();
        try
        {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        TxtUsuario = new javax.swing.JTextField();
        CmbSede = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        TxtClave = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        rSButtonMetro1 = new Componentes.RSButtonMetro();
        rSButtonMetro2 = new Componentes.RSButtonMetro();
        jLabel3 = new javax.swing.JLabel();
        JlMsg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 3, new java.awt.Color(0, 51, 102)));

        TxtUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuario", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        TxtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtUsuarioKeyPressed(evt);
            }
        });

        CmbSede.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CmbSede.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione ..." }));
        CmbSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbSedeActionPerformed(evt);
            }
        });
        CmbSede.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CmbSedeKeyPressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Inicio de Sesión");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        TxtClave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxtClave.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtClave.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contraseña", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        TxtClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtClaveKeyPressed(evt);
            }
        });

        rSButtonMetro1.setBackground(new java.awt.Color(0, 0, 0));
        rSButtonMetro1.setText("Cancelar");
        rSButtonMetro1.setColorHover(new java.awt.Color(0, 204, 204));
        rSButtonMetro1.setColorNormal(new java.awt.Color(0, 0, 0));
        rSButtonMetro1.setColorPressed(new java.awt.Color(51, 153, 0));
        rSButtonMetro1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rSButtonMetro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro1ActionPerformed(evt);
            }
        });

        rSButtonMetro2.setBackground(new java.awt.Color(204, 51, 0));
        rSButtonMetro2.setText("Aceptar");
        rSButtonMetro2.setColorHover(new java.awt.Color(153, 204, 0));
        rSButtonMetro2.setColorNormal(new java.awt.Color(204, 51, 0));
        rSButtonMetro2.setColorPressed(new java.awt.Color(51, 153, 0));
        rSButtonMetro2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rSButtonMetro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Sucursal :");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        JlMsg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JlMsg.setForeground(new java.awt.Color(0, 51, 0));
        JlMsg.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        JlMsg.setText(".");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtUsuario)
                    .addComponent(CmbSede, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtClave)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 75, Short.MAX_VALUE)
                        .addComponent(rSButtonMetro2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JlMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JlMsg)
                .addGap(18, 18, 18)
                .addComponent(TxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(TxtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CmbSede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSButtonMetro2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/Ruleta/LottoJuegoA.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void Limpiar()
    {
        TxtClave.setText("");
        TxtUsuario.setText("");
        CmbSede.setSelectedIndex(0);
        TxtUsuario.requestFocus();
    }
    
    void CargarBodegas()
    {
        String SqlCargarCajas = "";
        
        try
        {
            SqlCargarCajas = "SELECT BODEGA FROM BODEGAS ORDER BY CODIGO";
            ConeBD.RstBD = (ResultSet) ConeBD.StmBD.executeQuery(SqlCargarCajas);
            while (ConeBD.RstBD.next())
            {
                CmbSede.addItem((ConeBD.RstBD.getString("BODEGA")));
            }
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }
    }
    
    void SacarUsuario(String Usu)
    {
        String SqlSacarUsu = "";
        
        try
        {
            SqlSacarUsu = "SELECT * FROM SEGURIDAD WHERE NICK = '"+Usu+"'";
            ConeBD.RstBD = (ResultSet) ConeBD.StmBD.executeQuery(SqlSacarUsu);
            if (ConeBD.RstBD.next())
            {
                TxtClave.requestFocus();
            }   
            else
            {
                JOptionPane.showMessageDialog(null, "Usuario No existe ...");
                Limpiar();
            }
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }
    }
    
    void Ingreso()
    {
        String SqlIngresar = "", Nombre = "";
        try
        {
            SqlIngresar = "SELECT * FROM SEGURIDAD WHERE NICK = '"+TxtUsuario.getText()+"' AND CLAVE = '"+TxtClave.getText()+"'"
                    + " AND CODBODEGA = "+CodigoBodega;
            System.out.println(SqlIngresar);
            ConeBD.RstBD = (ResultSet) ConeBD.StmBD.executeQuery(SqlIngresar);
            if (ConeBD.RstBD.next())
            {
                if (ConeBD.RstBD.getString("TIPO").equals("1"))
                {
                    if (ConeBD.RstBD.getString("ESTADO").equals("1"))
                    {
                        Nombre = ConeBD.RstBD.getString("NOMBRE");                        
                        FrmPrincipal Pri = new FrmPrincipal();
                        Pri.Mostrar(CmbSede.getSelectedItem().toString());
                        Pri.setVisible(true);
                        dispose();                    
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Sin Permisos para Ingresar ...");
                        Limpiar();
                    }
                }
                else
                {
                    if (ConeBD.RstBD.getString("TIPO").equals("2"))
                    {
                        if (ConeBD.RstBD.getString("ESTADO").equals("1"))
                        {
                            Nombre = ConeBD.RstBD.getString("NOMBRE");   
                            FrmPrincipal Pri = new FrmPrincipal();
                            Pri.Mostrar(CmbSede.getSelectedItem().toString());
                            Pri.setVisible(true);
                            dispose();
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null, "Sin Permisos para Ingresar ...");
                            Limpiar();
                        }
                    }
                    else
                    {
                        if (ConeBD.RstBD.getString("TIPO").equals("3"))
                        {
                            if (ConeBD.RstBD.getString("ESTADO").equals("1"))
                            {
                                Nombre = ConeBD.RstBD.getString("NOMBRE");   
                                FrmPrincipal Pri = new FrmPrincipal();
                                Pri.Mostrar(CmbSede.getSelectedItem().toString());
                                Pri.setVisible(true);
                                dispose();
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null, "Sin Permisos para Ingresar ...");
                                Limpiar();
                            }
                        }
                    }
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "El Usuario No Existe / No tiene Permisos en la Caja o en la Bodega...");
                Limpiar();
            }
            
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }
            
    }
    
    
    private void TxtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtUsuarioKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) 
        {
            SacarUsuario(TxtUsuario.getText());
        }
    }//GEN-LAST:event_TxtUsuarioKeyPressed

    void SacarSucursal()
    {
        String NomBodega = CmbSede.getSelectedItem().toString(), SqlSacarCodigo = "";
        
        try
        {
            SqlSacarCodigo = "SELECT CODIGO FROM BODEGAS WHERE BODEGA = '"+NomBodega+"'";
            ConeBD.RstBD = (ResultSet) ConeBD.StmBD.executeQuery(SqlSacarCodigo);
            if (ConeBD.RstBD.next())
            {
                CodigoBodega = ConeBD.RstBD.getInt("CODIGO");
            }
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }
    }
    
    private void CmbSedeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CmbSedeKeyPressed
              
        
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) 
        {
            SacarSucursal();
            rSButtonMetro2.requestFocus();
        }
    }//GEN-LAST:event_CmbSedeKeyPressed

    private void TxtClaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtClaveKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) 
        {
            if (!(TxtClave.getText().equals(""))) 
            {
                CmbSede.requestFocus();
            } 
            else 
            {
                JOptionPane.showMessageDialog(null, "Debe Seleccionar Una Sucursal ... ");
            }
        }
    }//GEN-LAST:event_TxtClaveKeyPressed

    private void rSButtonMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_rSButtonMetro1ActionPerformed

    private void rSButtonMetro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro2ActionPerformed

        if (CmbSede.getSelectedIndex() != 0) 
        {
            SacarSucursal();
            Ingreso();
        } 
        else 
        {
            JOptionPane.showMessageDialog(null, "Debe Seleccionar una Sucursal ...");
        }

    }//GEN-LAST:event_rSButtonMetro2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ConeBD.Coneccion_BD();
        CargarBodegas();
    }//GEN-LAST:event_formWindowOpened

    private void CmbSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbSedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbSedeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInicioP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInicioP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInicioP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInicioP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmInicioP().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CmbSede;
    private javax.swing.JLabel JlMsg;
    private javax.swing.JPasswordField TxtClave;
    private javax.swing.JTextField TxtUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private Componentes.RSButtonMetro rSButtonMetro1;
    private Componentes.RSButtonMetro rSButtonMetro2;
    // End of variables declaration//GEN-END:variables
}
