/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Ruleta;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

import java.net.*;
import java.io.*;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.TimeZone;
import javax.swing.JViewport;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author DESINCO
 */
public class FrmPrincipal extends javax.swing.JFrame {

    
    Conexion ConeBD =  new Conexion();
    
   
    DefaultTableModel DatosHorarioLotto;
    String DatHorarioLotto[] =  new String[4];
    
    DefaultTableModel DatosLottoG;
    String DatLottoG[] =  new String[6];
    
    Timer Tiempo;
    java.util.Date Reloj;
    SimpleDateFormat Formato;
    
    String FechaF = "", SucJuegos = "", FechaJuego = "";
    
    Date fechaHTTP, FechaGeneral;
    
    DecimalFormat Convertir = new DecimalFormat("###,###.##");
    
    public FrmPrincipal() {
        
        initComponents();
        try
        {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }        
        this.setExtendedState(MAXIMIZED_BOTH); 
        TablaHorario.requestFocus();
        new IniciarHilo().start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        JlHora = new javax.swing.JLabel();
        JlFecha = new javax.swing.JLabel();
        JlSucursal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaGanadores = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaHorario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu5 = new javax.swing.JMenu();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenu6 = new javax.swing.JMenu();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        jMenuItem10 = new javax.swing.JMenuItem();
        jSeparator16 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMenu4 = new javax.swing.JMenu();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 5, 1, 5, new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/Ruleta/roulette_jackpot_gambling_gamble_casino_icon_225864 (1).png"))); // NOI18N
        jButton1.setToolTipText("Realizar Jugadas");
        jButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/Ruleta/roulette_lottery_giveaway_game_draw_icon_225899.png"))); // NOI18N
        jButton2.setToolTipText("Ver Resultados");
        jButton2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Iconos/IconV/if_money_299107.png"))); // NOI18N
        jButton3.setToolTipText("Realizar Pago");
        jButton3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Iconos/IconV/if_Cancel_728918.png"))); // NOI18N
        jButton4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        JlHora.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        JlHora.setForeground(new java.awt.Color(255, 255, 255));
        JlHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlHora.setText(".");

        JlFecha.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        JlFecha.setForeground(new java.awt.Color(255, 255, 255));
        JlFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlFecha.setText(".");

        JlSucursal.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        JlSucursal.setForeground(new java.awt.Color(255, 255, 255));
        JlSucursal.setText(".");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JlSucursal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JlFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JlHora, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JlHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JlFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JlSucursal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TablaGanadores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TablaGanadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaGanadores.setRowHeight(35);
        jScrollPane1.setViewportView(TablaGanadores);

        TablaHorario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TablaHorario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaHorario.setRowHeight(35);
        jScrollPane2.setViewportView(TablaHorario);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Lottos Ganadores");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Horario apuestas activas");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Dashboard");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(0, 153, 204)));
        jMenuBar1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(328, 45));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Iconos/IconV/if_Web_Developmen_1562687.png"))); // NOI18N
        jMenu1.setText("Configuración");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenu1.add(jSeparator1);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/icons/Security-Icon.png"))); // NOI18N
        jMenu5.setText("Sistema");
        jMenu5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenu5.add(jSeparator5);

        jMenuItem5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/icons/user_add.png"))); // NOI18N
        jMenuItem5.setText("Seguridad");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/icons/vcard_add.png"))); // NOI18N
        jMenuItem6.setText("Asociar Sucursal");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/icons/book_next.png"))); // NOI18N
        jMenuItem7.setText("Parametros");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);
        jMenu5.add(jSeparator6);

        jMenu1.add(jMenu5);
        jMenu1.add(jSeparator2);

        jMenuItem1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/icons/application_side_boxes.png"))); // NOI18N
        jMenuItem1.setText("Asignar Ruleta");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/icons/application_side_expand.png"))); // NOI18N
        jMenuItem2.setText("Horarios de Juego");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/icons/house.png"))); // NOI18N
        jMenuItem3.setText("Sucursales");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator3);

        jMenuItem4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/icons/cancel.png"))); // NOI18N
        jMenuItem4.setText("Salir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);
        jMenu1.add(jSeparator4);

        jMenuBar1.add(jMenu1);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones_1/iconfinder_12_avatar_2754577.png"))); // NOI18N
        jMenu6.setText("Operativo");
        jMenu6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenu6.add(jSeparator14);

        jMenuItem16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/icons/arrow_out.png"))); // NOI18N
        jMenuItem16.setText("Anular Juego");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem16);

        jMenuItem8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/icons/color_swatch.png"))); // NOI18N
        jMenuItem8.setText("Ver Resultados");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem8);

        jMenuItem9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/icons/money_add.png"))); // NOI18N
        jMenuItem9.setText("Realizar Pagos");
        jMenu6.add(jMenuItem9);
        jMenu6.add(jSeparator15);

        jMenuItem10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/icons/table_add.png"))); // NOI18N
        jMenuItem10.setText("Cerrar Juego");
        jMenu6.add(jMenuItem10);
        jMenu6.add(jSeparator16);

        jMenuBar1.add(jMenu6);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Iconos/IconV/if_gear__process__setting__engineering__2568282.png"))); // NOI18N
        jMenu2.setText("Administrativo");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenu2.add(jSeparator7);

        jMenuItem15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/icons/award_star_bronze_2.png"))); // NOI18N
        jMenuItem15.setText("Ingresar Resultados");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem15);

        jMenuItem20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/icons/application_cascade.png"))); // NOI18N
        jMenuItem20.setText("Listar Jugadas");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem20);
        jMenu2.add(jSeparator8);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Iconos/IconV/if_file_add_48761.png"))); // NOI18N
        jMenu3.setText("Informes");
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenu3.add(jSeparator10);

        jMenuItem18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/icons/page_white_acrobat.png"))); // NOI18N
        jMenuItem18.setText("Informe de Juegos");
        jMenu3.add(jMenuItem18);

        jMenuItem19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/icons/paste_plain.png"))); // NOI18N
        jMenuItem19.setText("Informes Ventas del Día");
        jMenu3.add(jMenuItem19);

        jMenuItem11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/icons/page_white_acrobat.png"))); // NOI18N
        jMenuItem11.setText("Informe de Resultados");
        jMenu3.add(jMenuItem11);

        jMenuItem12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/icons/page_white_acrobat.png"))); // NOI18N
        jMenuItem12.setText("Informe de Pagos");
        jMenu3.add(jMenuItem12);
        jMenu3.add(jSeparator11);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Iconos/IconV/if_7_2169614.png"))); // NOI18N
        jMenu4.setText("Estadisticas");
        jMenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenu4.add(jSeparator12);

        jMenuItem17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/icons/chart_bar.png"))); // NOI18N
        jMenuItem17.setText("Informe de Cierres");
        jMenu4.add(jMenuItem17);

        jMenuItem13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/icons/money_dollar.png"))); // NOI18N
        jMenuItem13.setText("Informe de Ingresos");
        jMenu4.add(jMenuItem13);

        jMenuItem14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/icons/money.png"))); // NOI18N
        jMenuItem14.setText("Informe de Utlidad");
        jMenu4.add(jMenuItem14);
        jMenu4.add(jSeparator13);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static Date obtenerFechaDesdeHTTP() {
        try 
        {
            URL url = new URL("https://www.google.com");
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
            conn.setRequestMethod("HEAD");
            conn.connect();
            
            long fechaServidor = conn.getDate();
            conn.disconnect();
            
            return new Date(fechaServidor);
        } 
        catch (Exception e) 
        {
            System.err.println("Error al obtener fecha HTTP: " + e.getMessage());
            return null;
        }
    }
    
    private class IniciarHilo extends Thread
    {
        boolean Ingreso = true;
        @Override
        public void run()
        {
            while (true)
            {
                if (Ingreso)
                {
                    try
                    {                        
                        Ingreso = false;
                        Thread.sleep(100_000);
                        MostrarTabla();
                        MostrarGanadores(FechaJuego);
                        System.out.println("Entro Actualizar 100 ms");
                    }
                    catch (Exception err)
                    {
                        err.printStackTrace();
                        break;
                    }
                }
                else
                {
                    Ingreso = true;
                    System.out.println("No Entro Actualizar 100 ms");
                }
            }
        }
    }
    
    
    public void Mostrar(String Sucursal)
    {
        SucJuegos = Sucursal;
        JlSucursal.setText("Sucura@l : "+Sucursal);
        this.setTitle("Lotto Animal - Ruleta v. 1.0"+ "Sucura@l : "+Sucursal);
    }
    
    void MostrarHora()
    {
        Formato = new SimpleDateFormat("HH:mm:ss");
        Tiempo = new Timer(1000, new ActionListener() 
        {
            public void actionPerformed(ActionEvent evt)
            {
                Reloj = new java.util.Date();
                JlHora.setText(Formato.format(Reloj));
            }
        });
        Tiempo.start();
    }
    
    void MostrarGanadores(String Fecha)
    {
        String SqlMostrarGanadores = "";
        
        TablaGanadores.clearSelection();
        DatosLottoG = new DefaultTableModel();
        TablaGanadores.setModel(DatosLottoG);
        DatosLottoG.addColumn("Radicado");
        DatosLottoG.addColumn("Lotto Animal");
        DatosLottoG.addColumn("Valor Ap. $");
        DatosLottoG.addColumn("Fecha");
        DatosLottoG.addColumn("Hora");
        DatosLottoG.addColumn("Hora Jugada");
        
        try
        {
            SqlMostrarGanadores = "SELECT hislottojuego.RADICADO AS NUMJUEGO, hislottojuego.CODANIMAL AS CODA,"
                    + " hislottojuego.ANIMAL AS NOMANIMAL, hislottojuego.VALOR AS VALORJ,"
                    + " hislottojuego.FECHA AS FECHA, hislottojuego.HORA AS HORAJ, ingresarganadores.DESCRIOCIONH AS HORAJUEGO"
                    + " FROM hislottojuego, ingresarganadores"
                    + " WHERE"
                    + " ingresarganadores.CODIGOA = hislottojuego.CODANIMAL AND ingresarganadores.CODIGOH = hislottojuego.CODIGOJ AND"
                    + " ingresarganadores.FECHA = '"+Fecha+"' AND hislottojuego.FECHA = '"+Fecha+"' AND hislottojuego.ESTADOP = 'A'";
            ConeBD.RstBD = (ResultSet) ConeBD.StmBD.executeQuery(SqlMostrarGanadores);
            System.out.println(SqlMostrarGanadores);
            while (ConeBD.RstBD.next())
            {
                DatLottoG[0] = ConeBD.RstBD.getString("NUMJUEGO");
                DatLottoG[1] = ConeBD.RstBD.getString("NOMANIMAL");
                DatLottoG[2] = String.valueOf(Convertir.format(ConeBD.RstBD.getDouble("VALORJ")));
                DatLottoG[3] = String.valueOf(ConeBD.RstBD.getDate("FECHA"));
                DatLottoG[4] = String.valueOf(ConeBD.RstBD.getTime("HORAJ"));
                DatLottoG[5] = ConeBD.RstBD.getString("HORAJUEGO");
                DatosLottoG.addRow(DatLottoG);
                
                int anchoColumna1 = 0;
                JViewport scroll1 =  (JViewport) TablaGanadores.getParent();
                int ancho1 = scroll1.getWidth();
                TableColumnModel modeloColumna1 = TablaGanadores.getColumnModel();
                TableColumn columnaTabla1;                
                for (int j = 0; j < TablaGanadores.getColumnCount(); j++)
                {
                    columnaTabla1 = modeloColumna1.getColumn(j);
                    switch(j)
                    {
                        case 0: anchoColumna1 = (30*ancho1)/100;
                            break;
                        case 1: anchoColumna1 = (30*ancho1)/100;
                            break;
                        case 2: anchoColumna1 = (30*ancho1)/100;
                            break;
                        case 3: anchoColumna1 = (30*ancho1)/100;
                            break;
                        case 4: anchoColumna1 = (30*ancho1)/100;
                            break;
                        case 5: anchoColumna1 = (70*ancho1)/100;
                            break;
                    }
                    columnaTabla1.setPreferredWidth(anchoColumna1);
                }
            }
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }
    }
    
    void MostrarTabla()
    {        
        Formato = new SimpleDateFormat("HH:mm:ss");
        Reloj = new java.util.Date();
        String Hora = (Formato.format(Reloj));
        
        String SqlMostrarTabla = "";
        TablaHorario.clearSelection();
        DatosHorarioLotto =  new DefaultTableModel();
        TablaHorario.setModel(DatosHorarioLotto);
        
        DatosHorarioLotto.addColumn("Codigo");
        DatosHorarioLotto.addColumn("Des. Juego");
        DatosHorarioLotto.addColumn("Hota Juego");
        
        try
        {
            SqlMostrarTabla = "SELECT * FROM horariojuego WHERE (HORA >= '"+Hora+"') AND ESTADO = 'A' ORDER BY NUM";
            //SqlMostrarTabla = "SELECT * FROM horariojuego WHERE ESTADO = 'A' ORDER BY NUM";
            System.out.println(SqlMostrarTabla);
            ConeBD.RstBD = (ResultSet) ConeBD.StmBD.executeQuery(SqlMostrarTabla);
            while (ConeBD.RstBD.next())
            {
                DatHorarioLotto[0] = String.valueOf(ConeBD.RstBD.getInt("NUM"));
                DatHorarioLotto[1] = ConeBD.RstBD.getString("DESCRIPCION");
                DatHorarioLotto[2] = String.valueOf(ConeBD.RstBD.getTime("HORA"));
                DatosHorarioLotto.addRow(DatHorarioLotto);
                
                int anchoColumna1 = 0;
                JViewport scroll1 =  (JViewport) TablaHorario.getParent();
                int ancho1 = scroll1.getWidth();
                TableColumnModel modeloColumna1 = TablaHorario.getColumnModel();
                TableColumn columnaTabla1;                
                for (int j = 0; j < TablaHorario.getColumnCount(); j++)
                {
                    columnaTabla1 = modeloColumna1.getColumn(j);
                    switch(j)
                    {
                        case 0: anchoColumna1 = (15*ancho1)/100;
                            break;
                        case 1: anchoColumna1 = (80*ancho1)/100;
                            break;
                        case 2: anchoColumna1 = (30*ancho1)/100;
                            break;
                    }
                    columnaTabla1.setPreferredWidth(anchoColumna1);
                }
                
            }
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }        
    }
    
    void SalirSistema()
    {
        System.exit(0);
        try
        {
            ConeBD.RstBD.close();
            ConeBD.StmBD.close();
            ConeBD.BD.close();
        }
        catch (Exception err)
        {
            err.printStackTrace();
        }
    }
    
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        SalirSistema();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        FrmDSeguridad Seg =  new FrmDSeguridad(this, rootPaneCheckingEnabled);
        Seg.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        FrmDAsoUsuarioSeg AsoS =  new FrmDAsoUsuarioSeg(this, rootPaneCheckingEnabled);
        AsoS.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        FrmDParametros Par =  new FrmDParametros(this, rootPaneCheckingEnabled);
        Par.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmDAsignarRuleta AsiR =  new FrmDAsignarRuleta(this, rootPaneCheckingEnabled);
        AsiR.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        FrmDSucursal Sucu =  new FrmDSucursal(this, rootPaneCheckingEnabled);
        Sucu.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FrmDTiempoJuego HoraJ = new FrmDTiempoJuego(this, rootPaneCheckingEnabled);
        HoraJ.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        formato.setTimeZone(TimeZone.getTimeZone("America/Bogota"));
        SimpleDateFormat F = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date Fecha = new java.util.Date();
        
        MostrarHora();
        ConeBD.Coneccion_BD();
        
                
        // Probar método HTTP
        fechaHTTP = obtenerFechaDesdeHTTP();
        if (fechaHTTP != null) 
        {
            //FECHA DE INTERNET
            System.out.println("Conexion HTTP");
            FechaGeneral = fechaHTTP;
            FechaF = String.valueOf(formato.format(fechaHTTP));
        }
        else
        {
            //FECHA LOCAL
            System.out.println("Conexion LOCAL");            
            FechaGeneral = Fecha;
            FechaF = String.valueOf(formato.format(Fecha));            
        }
        FechaJuego = String.valueOf(F.format(Fecha));
        JlFecha.setText(FechaF);
        MostrarTabla();
        MostrarGanadores(FechaJuego);
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        FrmDRealizarJuego Jugar = new FrmDRealizarJuego(this, rootPaneCheckingEnabled);
        Jugar.Mostrar(SucJuegos, FechaGeneral);
        Jugar.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        
        FrmDIngresarResultado InRe =  new FrmDIngresarResultado(this, rootPaneCheckingEnabled);
        InRe.Mostrar(SucJuegos, FechaGeneral);
        InRe.setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        
        FrmDVerResultados VerR = new FrmDVerResultados(this, rootPaneCheckingEnabled);
        VerR.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        FrmDVerResultados VerR = new FrmDVerResultados(this, rootPaneCheckingEnabled);
        VerR.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        
        FrmDAnularJuego Anu  = new FrmDAnularJuego(this, rootPaneCheckingEnabled);
        Anu.setVisible(true);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        SalirSistema();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        FrmDListarJugadas VerR =  new FrmDListarJugadas(this, rootPaneCheckingEnabled);
        VerR.setVisible(true);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlFecha;
    private javax.swing.JLabel JlHora;
    private javax.swing.JLabel JlSucursal;
    private javax.swing.JTable TablaGanadores;
    private javax.swing.JTable TablaHorario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator16;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    // End of variables declaration//GEN-END:variables
}
